### PR TITLE
[MRG] HW6

### PR DESCRIPTION
**Pull request by kjacks21**
## Description
**Goal**: Type Abstraction.
Liskov 7.11.

Instead of building an IntBag, complete the implementation of a generic version Bag.java and compare it to this generic version of IntSet: LiskovGenericSet.java.

Note that the rep has been chosen for you. Your code should be pretty simple. It won't be quite as simple as the set version, but it will be close. You should also implement repOk().

To answer Liskov's question about subtype relationships, find a relevant "Properties" rule. Your should code this up as an appropriate JUnit test.

Make it very easy for the GTA to understand your analysis of the subtyping question.

Again, I expect to see a robust discussion on Piazza about a relevant property.

## Tasks

- [x] Implement Bag.java
- [x] Implement `repOk()`
- [x] Implement JUnit tests

### CODE REVIEW

**Comment by 1000DS000000** [comment]
Should we split it up 2 methods each? with one person doing the additional JUnit test case for the properties rule

**Comment by kjacks21** [comment]
Sounds good.

**Comment by ngreenwald89** [comment]
for `remove`, should we throw an Exception if there's an attempt to remove an object not in the Bag?

**Comment by kjacks21** [comment]
> for remove, should we throw an Exception if there's an attempt to remove an object not in the Bag?

Perhaps we should follow the [javadocs](https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html#remove-java.lang.Object-) and return `null`?

**Comment by 1000DS000000** [comment]
I was thinking to follow what the GenericSet code had, which didn't throw any exception. It would just leave the list unchanged.
Also,  i thought we only had to do one JUnit test case for finding a properties rule.

**Comment by kjacks21** [comment]
Ah right, it has `void` in the signature so I agree with you on that. Should I delete the additional JUnit tests? I just assumed we were supposed to add more.

**Comment by 1000DS000000** [comment]
Possibly since the specs doesn't say anything about it, but i don't think it'll hurt to just keep them.

**Comment by kjacks21** [comment]
Ok. We good to merge and submit then?

**Comment by ngreenwald89** [comment]
Agreed

**Pull request merged**
