### PR TITLE
HW12.3

### PR DESCRIPTION
**Pull request by kjacks21**
Here is the code for `Period` and `MutablePeriod`. Oddly it isn't running and I am getting the following error:

image

When I should be getting output similar to:

```
Wed Nov 22 00:21:29 PST 2017 - Wed Nov 22 00:21:29 PST 1978
Wed Nov 22 00:21:29 PST 2017 - Wed Nov 22 00:21:29 PST 1969
```

Please take a look at what I have! Thanks!

### CODE REVIEW

**Comment by 1000DS000000** [comment]
to fix the error I think the period class needs to implement Serializable

**Comment by kjacks21** [comment]
Excellent. Thank you! We still need to add a story...any ideas on that?

**Comment by 1000DS000000** [comment]
I'm not really sure. Maybe we just explain that when we run the code from the book we see that the immutable period got changed and then provide a screenshot of the IDE with the code and the output.

**Comment by 1000DS000000** [comment]
so i started the story deliverable. I think there should be more to add though.

**Comment by 1000DS000000** [comment]
you can elaborate more of the story deliverable

**Comment by kjacks21** [comment]
submitted.

**Comment by kjacks21** [comment]
Feedback is 10.5/10

**Pull request merged**
