### PR TITLE
HW9

### PR DESCRIPTION
**Pull request by kjacks21**
From class. Do we want to do the extra credit?

### CODE REVIEW

**Comment by kjacks21** [comment]
Going to submit unless there are objections.

**Comment by ngreenwald89** [comment]
Let's wait a day. I'm going to look at the extra credit tonight/tomorrow. Do you know how to read an smv file?

**Comment by ngreenwald89** [comment]
Nevermind, reads with a text editor.

**Comment by ngreenwald89** [comment]
I didn't attempt the extra credit. @kjacks21 you are good to submit. Thanks!!

**Comment by kjacks21** [comment]
Submitted.

**Comment by kjacks21** [comment]
Feedback from grader - "Nice job!"

**Pull request merged**
